# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Locally Adaptive Regularization for Graph Estimation
NULL

#' Inner Loop using Autotune Lasso  
lasso_autotune <- function(X_X, X_Y, r_XY, lambdas, sigma2, n, s_22, y, Z, node, outer_iter, alpha, F_crit_values, lambda0 = -1, verbose_i = FALSE, penalize_diag = FALSE) {
    .Call(`_large_lasso_autotune`, X_X, X_Y, r_XY, lambdas, sigma2, n, s_22, y, Z, node, outer_iter, alpha, F_crit_values, lambda0, verbose_i, penalize_diag)
}

fit_large <- function(X, alpha = 0.02, penalize_diag = FALSE, thr = 0.05, maxit = 20L, verbose = TRUE) {
    .Call(`_large_fit_large`, X, alpha, penalize_diag, thr, maxit, verbose)
}

